### ISSUE TITLE
Could you possibly provide writeups?

### ISSUE THREAD

**Issue by punitdarji** [m6a-UdS/ssrf-lab#3]
Hi there,
I am creating OWASP top 10 vulnerable lab. I have seen your SSRF lab. I request you to share writeups for the tasks. Thank you.

**Comment by shivankar-madaan** [comment]
@PunitTailor55 
Here are the writeups
https://medium.com/poka-techblog/server-side-request-forgery-ssrf-attacks-part-1-the-basics-a42ba5cc244a
https://medium.com/poka-techblog/server-side-request-forgery-ssrf-attacks-part-2-fun-with-ipv4-addresses-eb51971e476d
https://medium.com/poka-techblog/server-side-request-forgery-ssrf-part-3-other-advanced-techniques-3f48cbcad27e

Thank you @m6a-UdS for the lab.

**Comment by m6a-UdS** [comment]
Hello all,

Thank you for your interest in the lab! This repo is a rather an old unmaintained version, you might want to take a look at [this version](https://github.com/m6a-UdS/dvca) which is a more complete derivative of this work.

I am also working on a more modern version with less dependencies (vs domains+TLS) and implemented in CDK, stay tuned :-)

You might also want to checkout the 2018-ish [Hackfest challenge](https://github.com/hackfestca/ssrf) that was also derived from this work: https://github.com/m6a-UdS/hf-ctf

Thank you,
